//! Goal24 Checkpoint 7 (Lane B) - native approval record types.
//!
//! Approval records are native/server-owned: a caller can never construct a
//! record, only carry an `ApprovalReferenceWire` whose real authority comes
//! from the native `ApprovalStore` lookup. No real GitHub token or API key is
//! ever stored.

use serde::{Deserialize, Serialize};

use crate::execution_broker::policy::ExecutionRiskPolicy;
use crate::execution_broker::types::AuthorityLevelWire;

// ---------------------------------------------------------------------------
// Approval grant states
// ---------------------------------------------------------------------------

/// Lifecycle of one native approval grant. Only `Granted` (and not expired,
/// not consumed, not revoked) can ever verify.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ApprovalStatus {
    Pending,
    Granted,
    Denied,
    Revoked,
    Consumed,
    Expired,
}

/// Trusted actor kinds allowed to grant a write approval in CP7. `model`,
/// `skill`, `provider` and `system` actors can never grant.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ActorKind {
    Owner,
    Admin,
}

// ---------------------------------------------------------------------------
// Approval record
// ---------------------------------------------------------------------------

/// Persistent approval record. The `token_reference` / `token_digest` pair is
/// generated by the native authority from secure random grant material; the
/// store keeps only the digest, never the material and never a credential.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ApprovalRecord {
    pub approval_id: String,
    #[serde(default)]
    pub approval_request_id: Option<String>,
    pub plan_id: String,
    /// SHA-256 over the canonical approval binding payload (see `digest.rs`).
    pub approval_binding_digest: String,
    pub capability_id: String,
    pub capability_version: String,
    /// Frozen copy of the compiled binding risk policy at grant time.
    pub risk_policy_snapshot: ExecutionRiskPolicy,
    pub actor_id: String,
    pub actor_kind: ActorKind,
    pub actor_authority: AuthorityLevelWire,
    pub policy_version: String,
    /// RFC3339, trusted native clock.
    pub granted_at: String,
    /// RFC3339, bounded: grant lifetime <= 15 minutes and <= plan expiry.
    pub expires_at: String,
    /// High-entropy native-generated reference (never caller supplied).
    pub token_reference: String,
    /// SHA-256 binding the grant material to the approval binding.
    pub token_digest: String,
    pub status: ApprovalStatus,
    #[serde(default)]
    pub consumed_at: Option<String>,
    #[serde(default)]
    pub execution_id: Option<String>,
}

impl ApprovalRecord {
    /// True while the record is verifiable (granted and not expired vs `now`).
    pub fn is_verifiable(&self, now: &chrono::DateTime<chrono::Utc>) -> bool {
        if self.status != ApprovalStatus::Granted {
            return false;
        }
        match chrono::DateTime::parse_from_rfc3339(&self.expires_at) {
            Ok(expires) => now < &expires.with_timezone(&chrono::Utc),
            Err(_) => false,
        }
    }
}
