// Generated by brain-server/scripts/generate-schema-artifacts.ts. Do not edit manually.
export const ENTITY_TYPES = ["principle","evidence","concept","tool","person","project","code_snippet","architecture_pattern","bug_vulnerability","business_logic","critical_review","capture_snapshot","memory","decision","goal","question","preference","event","task"] as const;
export const RELATIONSHIP_TYPES = ["derived_from","relates_to","depends_on","conflicts_with","extends","cites","belongs_to","supported_by","extracted_from","reviewed_by","references","decision_referenced","works_at","lives_in","studies_at","married_to","leads_to_conclusion","supersedes","superseded_by","revises","invalidates","historical_version_of","continues","reverses","opposed_by","outcome_of","learned_from","knows","uses","created_by"] as const;
export const NOTIFICATION_TYPES = ["insight","reminder","system","decay_warning","blindspot","proactive","proactive_question","conflict","consolidation"] as const;

export type EntityType = typeof ENTITY_TYPES[number];
export type RelationshipType = typeof RELATIONSHIP_TYPES[number];
export type NotificationType = typeof NOTIFICATION_TYPES[number];
