import { writeFileSync } from 'fs';
import { dirname, resolve } from 'path';
import { fileURLToPath, pathToFileURL } from 'url';

import { tools } from '../src/mcp-tools.js';
import {
  DOMAIN_SCHEMA_VERSION,
  ENTITY_TYPES,
  NOTIFICATION_TYPES,
  RELATIONSHIP_TYPES,
  SINGLE_VALUED_RELATIONSHIP_TYPES,
} from '../src/schema/domain.js';

const scriptDirectory = dirname(fileURLToPath(import.meta.url));
const repositoryRoot = resolve(scriptDirectory, '..', '..');

export function buildSchemaManifest() {
  return {
    schemaVersion: DOMAIN_SCHEMA_VERSION,
    source: 'brain-server/src/schema/domain.ts',
    entityTypes: [...ENTITY_TYPES],
    relationshipTypes: [...RELATIONSHIP_TYPES],
    singleValuedRelationshipTypes: [...SINGLE_VALUED_RELATIONSHIP_TYPES],
    notificationTypes: [...NOTIFICATION_TYPES],
    counts: {
      entityTypes: ENTITY_TYPES.length,
      relationshipTypes: RELATIONSHIP_TYPES.length,
      notificationTypes: NOTIFICATION_TYPES.length,
    },
  };
}

export function buildMcpToolManifest() {
  return {
    schemaVersion: DOMAIN_SCHEMA_VERSION,
    source: 'brain-server/src/mcp-tools.ts',
    toolCount: tools.length,
    tools: tools.map((tool) => ({
      name: tool.name,
      description: tool.description,
      inputSchema: tool.inputSchema,
    })),
  };
}

function toolGroup(name: string): string {
  if (name.includes('decision')) return 'Decision Intelligence';
  if (name.includes('decay')) return 'Proactive Cognition';
  if (name.includes('search') || name.includes('entity') || name.includes('relationship')
    || name.includes('memory') || name.includes('graph') || name.includes('capture')
    || name.includes('conclusion') || name.includes('core')) return 'Long-term Memory';
  return 'Operations';
}

export function buildCapabilityMatrix(): string {
  const grouped = new Map<string, string[]>();
  for (const tool of tools) {
    const group = toolGroup(tool.name);
    grouped.set(group, [...(grouped.get(group) || []), tool.name]);
  }

  const lines = [
    '# Generated Capability Matrix',
    '',
    '> Generated from `brain-server/src/schema/domain.ts` and `brain-server/src/mcp-tools.ts`.',
    '> This is an interface inventory, not a claim that every product workflow is Freeze-ready.',
    '',
    '## Domain schema',
    '',
    '| Kind | Count | Values |',
    '| --- | ---: | --- |',
    `| Entity types | ${ENTITY_TYPES.length} | ${ENTITY_TYPES.map((value) => `\`${value}\``).join(', ')} |`,
    `| Relationship types | ${RELATIONSHIP_TYPES.length} | ${RELATIONSHIP_TYPES.map((value) => `\`${value}\``).join(', ')} |`,
    `| Notification types | ${NOTIFICATION_TYPES.length} | ${NOTIFICATION_TYPES.map((value) => `\`${value}\``).join(', ')} |`,
    '',
    `## MCP tools (${tools.length})`,
    '',
    '| Product line | Tool count | Tools |',
    '| --- | ---: | --- |',
  ];
  for (const [group, names] of grouped) {
    lines.push(`| ${group} | ${names.length} | ${names.map((name) => `\`${name}\``).join(', ')} |`);
  }
  lines.push('');
  return lines.join('\n');
}

export function buildGeneratedTypeModule(): string {
  return [
    '// Generated by brain-server/scripts/generate-schema-artifacts.ts. Do not edit manually.',
    `export const ENTITY_TYPES = ${JSON.stringify(ENTITY_TYPES)} as const;`,
    `export const RELATIONSHIP_TYPES = ${JSON.stringify(RELATIONSHIP_TYPES)} as const;`,
    `export const NOTIFICATION_TYPES = ${JSON.stringify(NOTIFICATION_TYPES)} as const;`,
    '',
    'export type EntityType = typeof ENTITY_TYPES[number];',
    'export type RelationshipType = typeof RELATIONSHIP_TYPES[number];',
    'export type NotificationType = typeof NOTIFICATION_TYPES[number];',
    '',
  ].join('\n');
}

export function writeArtifacts(): void {
  writeFileSync(
    resolve(repositoryRoot, 'schema_manifest.json'),
    `${JSON.stringify(buildSchemaManifest(), null, 2)}\n`,
  );
  writeFileSync(
    resolve(repositoryRoot, 'mcp_tool_manifest.json'),
    `${JSON.stringify(buildMcpToolManifest(), null, 2)}\n`,
  );
  writeFileSync(
    resolve(repositoryRoot, 'generated_capability_matrix.md'),
    buildCapabilityMatrix(),
  );
  const generatedTypes = buildGeneratedTypeModule();
  writeFileSync(resolve(repositoryRoot, 'shared', 'generated-domain-types.ts'), generatedTypes);
  writeFileSync(resolve(repositoryRoot, 'mobile-app', 'src', 'types', 'generated-domain.ts'), generatedTypes);
}

if (process.argv[1] && import.meta.url === pathToFileURL(resolve(process.argv[1])).href) {
  writeArtifacts();
}
